### ISSUE TITLE
Spinny wheel of doom. Uncaught (in promise) Error: The "bosh" option is no longer supported, please use "serviceUrl" instead.

### ISSUE THREAD

**Issue by confuciussayuhm** [Music-Bot-for-Jitsi/Jimmi#154]
## Summary
Tried on multiple different Chromium based browsers (Brave, Chromium, Edge) and get the same error. The Jitsi SDK docs mention that `bosh` is deprecated: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api/#jitsiconnection

## Logs
```
xmpp.js:135 Uncaught (in promise) Error: The "bosh" option is no longer supported, please use "serviceUrl" instead
    at new Ra (xmpp.js:135:19)
    at new zh (JitsiConnection.js:24:17)
    at oo.D (Bot-0231bad4.js:4:26412)
    at async Bot-0231bad4.js:6:341
```
## Reproduction
- Install extension
- Navigate to app.jimmi.part
- Open Chromium Console
- Observe
- Cry

| Question | Answer |
| --- | --- |
| My operating system | Windows 11, WSL2 Ubuntu |
| Used browser with version | Brave->1.62.153 (121.0.6167.85), Edge->121.0.2277.83, Chromium->120.0.6099.129|

**Comment by p-fruck** [comment]
Thanks for reporting, I am a little short on time to debug. Can you please try http://app.jimmi.party/beta to test the hotfix?

**Comment by confuciussayuhm** [comment]
Gave http://app.jimmi.party/beta a go now. Get the following:
```
Bot-85252d40.js:4  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'getUserMedia')
    at y (Bot-85252d40.js:4:19453)
    at Bn (index-72b0b780.js:1:2200)
    at Array.map (<anonymous>)
    at index-72b0b780.js:4:3767
    at Vn (index-72b0b780.js:4:1569)
```

A different error! Promising!

**Comment by p-fruck** [comment]
Suspicious. What browser are you using? Does `navigator.mediaDevices.getUserMedia`result in the same error if you paste it directly into the browser console?

**Comment by p-fruck** [comment]
sorry, I didn't notice you actually sent your browser details. Is this because because you denied access to the microphone or something? Could you try a different browser? The PR above fixes the connectivity issue for me, tested with Chromium Version 121.0.6167.85 (Official Build) (64-bit)

**Comment by confuciussayuhm** [comment]
Super I get the `DJ Jim` bot in Jitsi now.

I can't seem to figure out how to actually play music though. If I look through the code I see references to googlevideo.com. Is the idea to manually update the rules.json and manifest.json files and then reimport the browser extension?

Feel like I am missing something obvious.

**Comment by p-fruck** [comment]
Do I understand correctly that your question is how to control the bot? The bot is controlled via the jitsi chat, there are the `!play` and `!queue` commands to play music from youtube. The the `!help` command to get a list of all possible commands

**Comment by p-fruck** [comment]
good point, I didn't notice it was missing in the readme.
This is a privacy feature of modern webbrowsers, essentially stating that you have to interact with the website (move the mouse and click somewhere) before the media devices (microphone) can be accessed. The bot is likely also muted inside your meeting room. Try to move to mouse in the `app.jimmi.party` interface to interact with the website and execute the play command again. This should cause the bot the bot to unmute and hopefully play something

**Comment by confuciussayuhm** [comment]
Hmm ok. So I've reloaded `app.jimmi.party` and clicked all the things (apart from typing my play command in the jitsi meeting windows) and nothing happens 😢

**Comment by p-fruck** [comment]
pushed some changes to /beta again. Unmuting should now be triggered properly. Please note that during playback two issues might occur:

- some of the instances might run into cors issue, in that case simply retry to get another randomized invidious instance for playback
- googlevideo might return 403 forbidden for some videos (idk why). In that case you wont be able to play that video and have to choose another song

**Comment by confuciussayuhm** [comment]
Just tried `/beta` and all the gestures/clcks/drags/etc. The video doesn't play and `DJ Jim` doesn't unmute in Jitsi 😢

**Comment by p-fruck** [comment]
seems like some caching issues with GitHub pages? I also removed `https://invidious.tiekoetter.com` from the list of invidious instances but I still experience CORS issues on the `/beta` branch (even though the domain is not included in the deployed website). I'll deploy to the main page and see if this changes anything. Otherwise we will have to wait until the cache expires. Very strange

**Comment by confuciussayuhm** [comment]
Seems the cached version is gone now. I don't see any references to https://invidious.tiekoetter.com. I do, however, get this new error in https://app.jimmi.party/:
```
Bot-703e75e4.js:4 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

**Comment by p-fruck** [comment]
is this an error or a warning? I think the warning can be ignored and the play command can be retried.
Also, are you using the form on the main page to connect to the jitsi instance or are you just reloading the page at `https://app.jimmi.party/#/bot/my.jitsi.instance/my-conference`? You should use the form to connect to the conference as this should circumvent such errors (maybe we should also add this to the usage guide :smile:)

**Comment by confuciussayuhm** [comment]
You legend. That was it. Working like a boss now.

**Comment by p-fruck** [comment]
Thank you very much for your patience! I've added some usage instructions and common issues to the README to make Jimmi easier to understand for new users. Feel free to open further issues if any problems occur or contribute code/documentation yourself if have the required time and motivation ;)
