### ISSUE TITLE
Setup Basic Repository

### ISSUE THREAD

**Issue by Simon-Walz** [Music-Bot-for-Jitsi/Jimmi#23]
> **As a** developer
> **I want** a structured base repository 
> **so that** I can implement features and tests in an orderly fashion.

## Description:
Setup svelte and deno project.

### 🟢 In scope:
- [x] #47
- [x] #27 
- [x] Create `trex` scripts for `run`, `build`, `lint`, `fmt` @p-fruck 
- [x] Setup linting for `frontend`/`backend` @p-fruck 

### 🔴 Not in scope:
- Start programming on features
- Setup unit tests structure

## What should be the result?
A setup that can be used to start working on features.

**Comment by antonplagemann** [comment]
ToDos:
- [ ] Write installation guide as markdown file (create a new `docs` folder)
- [ ] Add `vscode` workspace configuration file
- [ ] Create `trex` scripts for `run`, `build`, `lint`, `fmt`, `test`, `cov`
- [ ] Setup linting for `frontend`/`backend`
