### ISSUE TITLE
Document decisions and results

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#43]
> **As a** student
> **I want** my lecturer to be informed of all decisions and the reasoning behind them
> **so that** we all get a 1.0 grade.

## Description:
Document all decisions and cool things we made during development. This Issue is open end.

### 🟢 In scope:
- [x] Why Svelte?
- [x] Why Deno?
- [x] Why Velociraptor and trex and for what?
- [x] Why Snel and for what? (solved problems?)
- [x] Why opine (backend framework)?
- [x] Automated api client generation
- [x] All GitHub Actions automations (what and why)? (e.g. SonarCloud, Issue automation, CI/CD, devcontainer, CodeCov, etc.)
- [x] All external contributions
- [x] #56

### 🔴 Not in scope:
- Programming or everything that has not to do with documentation

## What should be the result?
A reasonable documentation that gives a good overview of what has been done and achieved.

**Comment by antonplagemann** [comment]
Waiting for #56

**Comment by antonplagemann** [comment]
- [x] Add trex contribution
- [x] Remove CodeCov & Code Climate
- [x] Add Docker and static binary compilation

**Comment by p-fruck** [comment]
Created the following issues in external projects:
```
https://github.com/denoland/deno/issues/13933
https://github.com/esm-dev/esm.sh/issues/275
https://github.com/jspm/project/issues/180
```

**Comment by antonplagemann** [comment]
- [x] Document new contributions
