### ISSUE TITLE
Setup Document Structure

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#56]
Setup document structure for architectural decisions, etc.

**Comment by antonplagemann** [comment]
@p-fruck 
I finished my work on #43. Feel free to implement your desired document structure (choose the same branch if you like). Afterwards you are welcome to mark #55 as `ready for review` 😊

**Comment by p-fruck** [comment]
@antonplagemann  Looks good to me :+1:
