### ISSUE TITLE
[EPIC] Develop Backend REST-API

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#71]
> **As a** developer
> **I want** a well documented REST-endpoint for communication with the backend
> **so that** everyone can use jimmi with their own frontend.

## Description:
Develop a REST-API with Deno and Opine in the Jimmi backend that provides clean and simple endpoints for the jimmi frontend and others. Use old code when possible, do refactoring as needed and take care of good exception handling (not yet there). Use the old code to find all methods and api calls needed for the jimmi frontend. Implement the API iteratively and add endpoints as they are needed. Use `/api` as base for every endpoint. User swagger inline JSDoc comments to document all created endpoints.

### 🟢 In scope:
- [x] Create an `api` folder with all contents inside the `backend` folder.
- [x] #72
- [x] #73
- [x] #74
- [ ] **Low priority**: Create an endpoint `/api/instances/<id>/jitsi` for switching to a new jitsi room.

### 🔴 Not in scope:
- Direct interactions with the jitsi api (use the provided api wrapper)
- Direct interactions with the youtube or invidious api (use the provided module)
- Frontend stuff

## What should be the result?
A full documented and well structured REST api that has varoius endpoints that can be used with the jimmi frontend or other applications.

**Comment by p-fruck** [comment]
> * **Low priority**: Create an endpoint `/api/instances//jitsi for switching to a new jitsi room.

Should we even implement this or simply create a new instance targeting a new jitsi room?
