### ISSUE TITLE
[EPIC] Implement Web-Socket Connection between Frontend and Backend

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#75]
> **As a** developer
> **I want** a a web-socket connection for communicating between frontend and backend
> **so that** events can be easily dispatched without the overhead of single http requests.

## Description:
Implement a Web-Socket Connection between Frontend and Backend for dispatching of events (e.g. user joined or music controls). Use old code if possible, do refactoring as needed and take care of good exception handling (not yet there).

### 🟢 In scope:
- [x] #87
- [x] #88
- [x] #89

### 🔴 Not in scope:
- Other api endpoints
- Web-socket message implementations

## What should be the result?
A working backend endpoint `/api/instances/<id>/socket` that creates a websocket. A frontend implementation in a `Socket.ts` file that can be used by other components to communicate with the backend and receive events.

**Comment by p-fruck** [comment]
Closing this as v2 release has been dropped
