### ISSUE TITLE
[EPIC] Setup Frontend using Tailwind 3

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#76]
> **As a** user
> **I want** want an easy and beauty frontend
> **so that** I can control all aspects of jimmi with ease.

## Description:
Setup a frontend using [Tabler](https://tabler.io/). Take care of a good structure. Use code from the old (Tailwind 2) frontend when possible, do refactoring as needed and take care of good exception handling (not yet there). Use dynamic colors (primary and secondary color are defined as theme) in contrast to the hardcoded colors in the old backend. 

### 🟢 In scope:
- [x] #90
- [x] #91
- [x] #92
- [x] #93

### 🔴 Not in scope:
- Backend implementations
- Api clients (use the generated one)

## What should be the result?
A working frontend with the components described.

**Comment by p-fruck** [comment]
Misleading (tabler vs tailwind) and already achieved in v2 for whatever reason.
