### ISSUE TITLE
Implement Backend Web-Socket Endpoint

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#87]
> **As a** developer
> **I want** to have a websocket endpoint in the backend
> **so that** I can communicate events e.g. music stopped) to the frontend in real time.

## Description:
Implement a web socket endpoint in the backend. Check if this can be realized using Opine [(see examples)](https://deno.land/x/opine@2.1.2/examples/websockets). If not check if it can be done using `socket.io`. Use a separate file for your implementation. 

### 🟢 In scope:
- [ ] Implement a `Socket` class that creates a new web socket
- [ ] Add an `/api/instances/<id>/socket` api endpoint that creates a new socket and returns it

### 🔴 Not in scope:
- Frontend implementation of the web socket
- Web socket documentation

## What should be the result?
A working web socket implementation in the backend.

**Comment by p-fruck** [comment]
Closing this as v2 release has been dropped
