### ISSUE TITLE
Implement Frontend Web-Socket

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#88]
> **As a** developer
> **I want** to have a websocket class in the frontend
> **so that** I can receive events e.g. music stopped) from the backend in real time.

## Description:
Implement a web socket class in the frontend. Check if this can be realized using Opine [(see client examples)](https://deno.land/x/opine@2.1.2/examples/websockets). If not, check if it can be done the native browser api. Use a separate file for your implementation. 

### 🟢 In scope:
- [ ] Implement a `Socket` class that creates a new web socket, opens a backend connection. and can be imported by other modules for registering callback listening functions.
- [ ] Add/test functionality to receive messages and pass them to the caller (no modification here)
- [ ] Create default listeners for `open`, `close`, etc.

### 🔴 Not in scope:
- Backend implementation of the web socket
- Web socket documentation

## What should be the result?
A working web socket implementation in the frontend.

**Comment by p-fruck** [comment]
Closing this as v2 release has been dropped
