### ISSUE TITLE
Create Web-Socket Documentation

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#89]
> **As a** developer
> **I want** to have a websocket documentation
> **so that** there is no confusion about what can be send and received using the websocket.

## Description:
Check and create a good documentation structure for everything we want to send through the web socket connection (maybe using the [async api](https://www.asyncapi.com/) with inline code comments.

### 🟢 In scope:
- [ ] Implement good documentation structure for everything that will be sent using the websocket
- [ ] Create documentation for all existing message and event types

### 🔴 Not in scope:
- Functionality implementations

## What should be the result?
A reasonable web socket documentation like we have for the backend REST api.

**Comment by p-fruck** [comment]
Closing this as v2 release has been dropped
