### ISSUE TITLE
Setup Tailwind Frontend

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/Jimmi#90]
> **As a** developer
> **I want** to have well structured frontend
> **so that** I can add fancy features.

## Description:
Set up a frontend with [tabler](https://tabler.io/). Take care of a good structure.

### 🟢 In scope:
- [x] Frontend setup

### 🔴 Not in scope:
- Frontend features

## What should be the result?
A working basic frontend, maybe with sample pages or data.

**Comment by p-fruck** [comment]
Because of our timely limitations, I will implement the frontend using Tailwind instead of Tabler because I do not have the time to learn a completely new framework.
